- hosts: "tag_Name_{{type}}"
  connection: local
  gather_facts: False
  pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
  user: ubuntu
  sudo: yes

  tasks:
    - name: Hello server
      shell: uname -a
