- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
  user: ubuntu
  sudo: yes
  tasks:
    - ec2_facts:
    - debug: msg= "{{ hostvars['ec2'] }}"

    # - name: destroy all instances
    #   ec2: state='absent'
    #        instance_type={{ ec2_instance_type }}
    #        group={{ ec2_security_group }}
    #        region={{ ec2_region }}
    #        wait=true
    #   with_items: hostvars[inventory_hostname]['ec2_instance_id']
