- name: terminate single instance
  hosts: "tag_Name_{{type}}"
  # hosts: "tag_Name_{{type}}"
  tasks:
    - action: ec2_facts
    - name: terminating single instance
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"


# - hosts: "tag_Name_{{type}}"
#   gather_facts: False
#   pre_tasks:
#     - include_vars: ec2_vars/{{type}}.yml
#   user: ubuntu
#   sudo: yes
#   tasks:
#     # - ec2_facts:
#     # - debug: msg= "{{type}}"
#
#     - name: destroy all instances
#       ec2: state='absent'
#            instance_type={{ ec2_instance_type }}
#            group={{ ec2_security_group }}
#            region={{ ec2_region }}
#            wait=true
#       # with_items: hostvars[inventory_hostname]['ec2_instance_id']
